### ISSUE TITLE
Possibilité de rendre l'adresse email obligatoire pour partciper

### ISSUE THREAD

**Issue by meldianen** [framasoft/framadate#2]
Bonjour,
Je viens de faire l'expérience qui motive cette demande.
Nous avons créé un sondage pour déterminer une date et un horaire pour une réunion.
Le lien a été envoyé à notre liste de diffusion.
Mais nous avons également fait de la publicité sur les réseaux sociaux en mettant le lien vers le sondage. Et là impossible de contacter les participants supplémentaires.
Serait-il possible d'ajouter un champ email lors de la création du sondage ?

Merci de votre attention et merci pour vos outils nombreux et très utiles.
Cordialement,
Vincent

**Comment by FramaJosephK** [comment]
Je clos le sujet ici car Framasoft n'utilise pas Github pour la gestion de ses projets.

Ceci étant, l'ajout d'un champ email est une demande récurrente et très pertinente mais nous n'avons pas encore eu le temps de la mettre en œuvre.
En tout cas, l'issue est ouverte sur notre dépôt Gitlab. Si vous voulez suivre son évolution ou poursuivre la discussion, ça se passe par là : https://git.framasoft.org/framasoft/framadate/issues/38
