### ISSUE TITLE
Refonte du code source ?

### ISSUE THREAD

**Issue by romainletendart** [framasoft/framadate#37]
Bonjour,

Après avoir parcouru rapidement le code source dans son état actuel, j'ai relevé plusieurs points qui, à mon avis, peuvent présenter un frein à de potentielles contributions extérieures.

Tout d'abord, le code, les commentaires et les noms de fichiers sont pour la majeure partie en français. Ainsi, il est quasiment impossible pour un contributeur non-francophone de contribuer.

Ensuite, il n'y a pas de séparation (au niveau fichier) entre la partie graphique et la partie logique de l'application. Or, des frameworks tels que CodeIgniter (ou autres) permettent de faire cela très simplement et sans gros impact sur les performances.

Je pense aussi qu'il manque des tests pour éviter la régression suite aux différents ajout de fonctionnalités et/ou corrections de bugs.

L'organisation des fichiers pourrait aussi être améliorée.

Ma question est donc la suivante :
Une refonte du code source est-elle prévue ?

**Comment by FramaJosephK** [comment]
La refonte est bien avancée.
Tout se passe sur Gitlab sur la branche develop (le workflow pour participer est décrit dans le readme de cette branch)
https://git.framasoft.org/framasoft/framadate
