### ISSUE TITLE
Sélection plus rapide de date multiples par plage, avec simple choix de début et fin

### ISSUE THREAD

**Issue by Lucas-C** [framasoft/framadate#40]
Tout est dans le titre :)

Je viens de sélectionner à la main tout un mois de jours successifs et c'est assez laborieux... À raison d'à peu près 4 clics par jour, c'est un peu décourageant.

Je vois deux solutions:
- ajouter des inputs _dateRangeStart_ & _dateRangeEnd_ au formulaire
- une solution plus légère en terme de développement mais moins "user-friendly" : un morceau de code Javascript côté client se chargerait d'ajouter "en batch" un nouvel _input_ par jour dans la plage de dates selectionnées.

Suis-je assez clar dans mes explications ?
Quelle alternative pensez-vous est la meilleure ?

Je me propose de travailler dessus et de soumettre un "pull request", si vous les acceptez.

Enfin, si l'effort technique est trop lourd, il existe une mitigation assez simple qui pourrait déjà un peu améliorer la prise en main de l'interface. Actuellement pour chaque _input_ le calendrier affiche initialement le mois courant. Lorsqu'on sélectionne des dates jusqu'au mois suivant, il est très laborieux et source d'erreur de devoir, à chaque nouveau jour ajouté, changer de mois. Sélectionner le mois de la dernière date entrée comme valeur par défaut serait bien plus agréable d'utilisation.

**Comment by FramaJosephK** [comment]
Framasoft n'utilise pas Github pour la gestion de ses projets.
Votre issue est reportée sur notre Gitlab
https://git.framasoft.org/framasoft/framadate/issues/72

Je vous invite à poursuivre la discussion là-bas et si vous voulez participer au développement vous êtes le bienvenu. On a fait un peu de ménage (et on y est encore :) ), le workflow est décrit dans le readme de la branch develop.
