### ISSUE TITLE
Erreur en prod en soumettant une réponse

### ISSUE THREAD

**Issue by Psycojoker** [framasoft/framadate#41]
Salut les cocos,

J'ai répondu à un sondage vers 21h20 aujourd'hui et je me suis tapé ce fabuleux warning php en haut de la page:

Warning: Missing argument 4 for sendEmail(), called in /public/teleragno.fr/www/opensondage/studs.php on line 179 and defined in /public/teleragno.fr/www/opensondage/fonctions.php on line 167 Warning: Missing argument 5 for sendEmail(), called in /public/teleragno.fr/www/opensondage/studs.php on line 179 and defined in /public/teleragno.fr/www/opensondage/fonctions.php on line 167 Notice: Undefined variable: headers in /public/teleragno.fr/www/opensondage/fonctions.php on line 185 Notice: Undefined variable: headers in /public/teleragno.fr/www/opensondage/fonctions.php on line 186 Notice: Undefined variable: param in /public/teleragno.fr/www/opensondage/fonctions.php on line 193 

Bisous,

**Comment by FramaJosephK** [comment]
Aucune idée de ce qui peut provoquer ce message d'erreur. Est-ce que vous utilisez la dernière version de Framadate (v0.8) ?
https://git.framasoft.org/framasoft/framadate
La procédure d'installation a un peu changé depuis opensondage. Vous trouverez un tutoriel détaillé là : 
http://framacloud.org/cultiver-son-jardin/installation-de-framadate/

Par ailleurs, Framasoft utilise GitLab pour le développement de ses logiciels libres. Nos dépôts Github ne sont que des miroirs. Il est préférable que vous ouvriez vos issues là-bas pour obtenir plus rapidement une réponse :
https://git.framasoft.org/framasoft/framadate/issues
