### ISSUE TITLE
Add possibility to set default language to users

### ISSUE THREAD

**Issue by brunetton** [framasoft/framadate#42]
Hi, 

I often use Framadates with French people. And they always complain about going onto an English poll. 
I think that we should add an option on url like lang=fr to control default poll language

**Comment by FramaJosephK** [comment]
Framasoft uses GitLab for the development of its free softwares. Our Github repositories are only mirrors.
Your issue is copied on Gitlab
https://git.framasoft.org/framasoft/framadate/issues/71
