### ISSUE TITLE
Erreur d'url si le nom du site commence par admin

### ISSUE THREAD

**Issue by nethenic** [framasoft/framadate#43]
Bonjour ! Super fork, j'adore :)
Petit problème cependant, si l'url du site est `admin.exemple.fr` alors la règle présente dans bandeaux.php `str_replace('/admin','', Utils::get_server_name())` cause problème puisque l'url devient `/.exemple.fr/` (ou un truc dans le genre).

J'avoue je n'ai pas de solution toute faite à proposer (il faudrait que je chercher d'abord la raison du str_replace) et le problème est certes mineur et circonscrit à ce cas précis, mais je voulais le signaler.

**Comment by FramaJosephK** [comment]
Framasoft n'utilise pas Github pour la gestion de ses projets.
Votre issue est reportée sur notre Gitlab
https://git.framasoft.org/framasoft/framadate/issues/70
