### ISSUE TITLE
Selection perdue si on oublie de préciser un nom

### ISSUE THREAD

**Issue by olethanh** [framasoft/framadate#45]
Si on ne remplis pas le champs nom, on a un message d'erreur et ils perds toutes notre selections qu'il faut rentrer a nouveau

**Comment by FramaJosephK** [comment]
C'est corrigé sur la version 0.9 (pas encore finalisée) :
https://git.framasoft.org/framasoft/framadate/issues/66

Je ferme l'issue ici car Framasoft n'utilise pas Github pour la gestion de ses projets.
