### ISSUE TITLE
mettre le bouton d'édition d'une ligne à gauche du nom

### ISSUE THREAD

**Issue by maieul** [framasoft/framadate#47]
Pas de raison de lire toute la ligne pour vouloir ensuite l'éditée. À gauche du nom  (à la doodle) serait plus pratique.

**Comment by FramaJosephK** [comment]
Framasoft n'utilise pas Github pour la gestion de ses projets.
Votre issue est reportée sur notre Gitlab
https://git.framasoft.org/framasoft/framadate/issues/69

**Comment by maieul** [comment]
a ok, merci. je savais plus où trouver cela. je note.
