### ISSUE TITLE
possibilité de modifier le nom

### ISSUE THREAD

**Issue by MaximeCheramy** [framasoft/framadate#51]
Un des utilisateurs du sondage a fait une faute dans son nom et il se plaint maintenant de ne pas pouvoir corriger. Même en admin je n'ai pas cette possibilité là.

**Comment by FramaJosephK** [comment]
Framasoft n'utilise pas Github pour la gestion de ses projets.
Votre issue est reportée sur notre Gitlab
https://git.framasoft.org/framasoft/framadate/issues/68
