### ISSUE TITLE
Problem with concurent edition: deleting choice while ppl are voting

### ISSUE THREAD

**Issue by saimonn** [framasoft/framadate#52]
This is a screenshot of the bug:
![cvtuvooxiaa5lkr](https://cloud.githubusercontent.com/assets/6391720/11657412/d3149aaa-9dbc-11e5-9294-f4eafe818ee6.png)
The initial poll had 4 choice of dates. I (the owner of the poll) removed two of them, while some people were already connected and filling forms.

I can send the poll URL in private if needed.

**Comment by tcitworld** [comment]
Please reopen if this is still the case on recent versions.
