### ISSUE TITLE
Installation fails because vendor folder is missing.

### ISSUE THREAD

**Issue by drudgede** [framasoft/framadate#53]
When I try to install framadate I get the PHP error:

Warning: require_once(/www/htdocs/myusername/termin/app/inc/../../vendor/autoload.php): failed to open stream: No such file or directory in /www/htdocs/myusername/termin/app/inc/init.php on line 23

Fatal error: require_once(): Failed opening required '/www/htdocs/myusername/termin/app/inc/../../vendor/autoload.php' (include_path='.:/usr/share/php:..') in /www/htdocs/myusername/termin/app/inc/init.php on line 23

I didn't found the vendor folder at all in the repository. Since vendor is an entry in the .gitignore-file, I think it isn't in the repo intentionally. Are there any prerequisites missing? Sorry, I am not able to speak French and tried to understand the install instructions somehow.

**Comment by pascalchevrel** [comment]
You need to install the dependencies with Composer, the PHP dependency manager:
https://getcomposer.org/

**Comment by drudgede** [comment]
Thanks, haven't read it in the installation instructions. Now it works fine!

**Comment by rototom** [comment]
Same problem here and I dont see instructions of how to install dependencies.
(I dont speak french...)

**Comment by Zitroanen** [comment]
@pascalchevrel can you tell me what to do with composer to install framadate correctly? it would be verry nice cause the install instruction is actually dead. :/

**Comment by pascalchevrel** [comment]
https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies
