### ISSUE TITLE
Cannot add date range

### ISSUE THREAD

**Issue by epatpol** [framasoft/framadate#62]
I don't know if the app being hosted on framadate.org is the latest, so maybe this has been fixed, but I cannot use the calendar button to add date ranges on chromium (latest version) on Ubuntu 14.04. See the attached picture for what I mean. Clicking on the calendar below the modal dialog closes the modal dialog as it loses its focus. 

![screenshot from 2016-11-08 14 29 38](https://cloud.githubusercontent.com/assets/2881761/20113836/0ba3558a-a5c0-11e6-8f6f-f94630e5c24a.png)

**Comment by tcitworld** [comment]
Now at https://framagit.org/framasoft/framadate/issues/347
