### ISSUE TITLE
[Feature request] Accessibility: increase color contrast

### ISSUE THREAD

**Issue by jibe-b** [framasoft/framadate#66]
The Green-Orange-Red colors choosen to indicate if someone is available/possibly available/not available is not much contrasted. Color-blind people might find it complicated to differentiate between answers.

This is part of the general question of accessibility. If this brings up other issues, I will try to provide some help on this.

**Comment by tcitworld** [comment]
Issue now at https://framagit.org/framasoft/framadate/issues/346
