### ISSUE TITLE
Day headers formatted wrong in certain browsers

### ISSUE THREAD

**Issue by stevenroose** [framasoft/framadate#67]
I made a poll recently **on the public version of Framatade** of which the headers looked like this on my machine (**Arch Linux with Chrome 60.0.3112.40 (Official Build) beta (64-bit)**):
![](https://i.imgur.com/cjMtOt4.png)

On my friend's computer (**Windows 7 Pro with Chrome 59.0.3071.115 (Official Build) (64-bit)**), they showed up like this:
![](https://i.imgur.com/4SXNFjK.png)

And on another friends mobile (no specs, can ask if requested), they showed up like this as well.
![](https://i.imgur.com/HpwfcDD.png)

My phone (**Android 6.0.1 with Chrome 59.0.3071.125**) it shows the normal column headers.

I guess it could also be a locale issue. I have all my locales set to US English, but considering the column header using "August", I guess the Windows is also configured in English.

--------
(The fact that on mobile it's impossible to see more than one or two columns (on my phone as well, even though the column headers show up correctly) is a separate issue. But if Framadate doesn't intend to be mobile-friendly, that's ok. Tell me if I should report that separately.)

**Comment by iamirm** [comment]
+1!!

**Comment by tcitworld** [comment]
Moved over to https://framagit.org/framasoft/framadate/issues/344
