### ISSUE TITLE
mysql error because of timestamp value

### ISSUE THREAD

**Issue by hajika** [framasoft/framadate#68]
I got an error while installing because in 

https://github.com/framasoft/framadate/blob/master/app/classes/Framadate/Migration/From_0_0_to_0_8_Migration.php line 75
https://github.com/framasoft/framadate/blob/master/app/classes/Framadate/Migration/From_0_8_to_0_9_Migration.php line 93

there are default values missing. That throw error `Error in query (1067): Invalid default value for 'date_fin' ` for me

**Comment by tcitworld** [comment]
Hi,

It should be fixed since Framadate 1.1, see https://framagit.org/framasoft/framadate/issues/224.
