### ISSUE TITLE
Install problem following wiki

### ISSUE THREAD

**Issue by pdgaaa** [framasoft/framadate#70]
Following https://framagit.org/framasoft/framadate/wikis/Install/Install

When I unzip the latest.zip, rights/permissions are not good on directories, it misses the 'x'/execution.

I download the latest 1.1.4 release on github, unzip it, the permissions are good.

I dowload the latest 1.1.4 master release on framagit, it's ok.

Someone can correct the link in the wiki at framagit ?

**Comment by tcitworld** [comment]
Closed in favour of https://framagit.org/framasoft/framadate/issues/342
